# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/whisper',
                'doc_host': 'https://Lekja00160612.github.io',
                'git_url': 'https://github.com/Lekja00160612/whisper',
                'lib_path': 'whisper'},
  'syms': {'whisper.core': {'whisper.core.foo': ('core.html#foo', 'whisper/core.py')}}}
